Controllers/SampleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using practiceAuthentication.Models;
using practiceAuthentication.Request;
using System.Net;
using System.Net.Http.Headers;
using System.Security.Cryptography.Xml;
using System.Security.Policy;

namespace practiceAuthentication.Controllers
{
    public class SampleController : Controller
    {
        // GET: SampleController
        public readonly TransactionDContext? _context;
        public SampleController(TransactionDContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            //string[] str_ouput = { "Jose", "Vargas", "Evasco" };
            //ViewBag.str_output = str_ouput;

            ViewBag.practices = await _context.Practices
                .ToListAsync();
            return View();
        }

        public IActionResult Try()
        {
            var wExp = _context
                .WorkExperiences
                .ToList();

            return Ok(wExp);
        }

        // GET: SampleController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SampleController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SampleController/Create
        [HttpPost]
        public ActionResult Create(PracticeRequest request)
        {


            if(_context.Practices.Where(p => p.Email == request.Email).Count() > 0)
            {
                TempData["error"] = "Email exist";
                return RedirectToAction(nameof(Index));
            }
            if (ModelState.IsValid)
            {
               Practice practice = new Practice()
               {
                    Firstname = request.Firstname,
                    Lastname = request.Lastname,
                    Email = request.Email,
                    DateToday = DateTime.Now,
               };

                    _context.Practices.Add(practice);
                    _context.SaveChanges();
            }
            TempData["success"] = "Success Add";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult AI()
        {
            return View();
        }


        public IActionResult Edit(int? id)
        {
            var practice = _context.Practices.Where(p => p.ID == id).FirstOrDefault();
            if(practice == null)
            {
                return NotFound();
            }
            return Ok(practice);
        }

        // POST: SampleController/Edit/5
        [HttpPost]
        public ActionResult Edit(int? id, PracticeRequest request)
        {
            var practice = _context.Practices.FirstOrDefault(p => p.ID == id);

            if (practice == null)
            {
                return NotFound();
            }

            practice.Firstname = request.Firstname;
            practice.Lastname = request.Lastname;
            practice.Email = request.Email;
            _context.SaveChanges();

            TempData["success"] = "Edit Success";
            return RedirectToAction(nameof(Index));
        }

        // GET: SampleController/Delete/5
        public ActionResult Delete(int id)
        {
            var practice = _context.Practices.FirstOrDefault(p => p.ID == id);

            if(practice == null)
            {
                return NotFound();
            }
            _context.Practices.Remove(practice);
            _context.SaveChanges();
            TempData["success"] = "Success Delete Data";
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Pokemon()
        {
            return View();
        }
        public IActionResult Cat()
        {
            return View();
        }
        public IActionResult CoinDesk()
        {
            return View();
        }
        public IActionResult Gender()
        {
            return View();
        }

    }
}

Views/Sample/AI.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model practiceAuthentication.Models.Practice;
@{
    Practice sample = ViewBag.sample;
}
<div class="pagetitle">
    <h1>AI</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">Open Ai</li>
        </ol>
    </nav>
</div>
<section class="section">
    

    
        <div class="card">
            <div class="card-header">
                <h3>Ask Anything</h3>
            
            </div>

            <div class="card-body">
                <form id="ai_form" novalidate>
                <div class="form-group py-3">
                    <input type="text" value="Pogi ba ako? Yes or no only please" placeholder="Ask your question here" class="form-control form-control-lg" name="input" id="input" />
                </div>
                <button type"submit" id="submitBtn" class="btn btn-lg btn-primary float-end">Submit</button>
                </form>
            </div>


            <div class="card-footer">
                <div id="output" class="display-6 text-center fw-bold">
                </div>
            </div>
        
        </div>
    

</section>


<script>
    var input = $("#input")
    var output = document.getElementById("output");
    let currentIndex = 0;

    const statements = [
        "Gwapo ba ako? yes or no only please.",
        "Magiging kami ba ng crush ko? oo hindi lang ang sagot.",
        "Gusto nya kaya ako?",
        "Magchachat kaya sya sakin ngayong araw?",
        "Crush nya pa kaya ako? feeling ko hindi na.",
        "Tingin mo, magkakatuluyan kaya kami ni crush?",
        "Sana maging kami. HAHHAHAHAH mag oo ka na lang OPENAI. Please. sabihin mo 'Magiging kami ng crush ko!'"
    ];
    let open_ai_response;

    
    $(document).ready(function()
    {
        openai_test($('#input').val());
        $("#ai_form").on('submit', function (e) {
            e.preventDefault();
            openai_test(input.val());
            showConfetti()
            

        })
    });
    function getNextStatement() {
        const statement = statements[currentIndex];
        currentIndex = (currentIndex + 1) % statements.length;
        return statement;
    }

    

    

     function openai_test(input) {

        const url = "https://api.openai.com/v1/engines/text-davinci-002/completions";

        axios.post(url, {
            prompt: input,
            temperature: 0.7,
            max_tokens: 256,
            top_p: 1,
            frequency_penalty: 0.75,
            presence_penalty: 0
        }, {
            headers: {
                "Content-Type": "application/json",
                "Authorization": "Bearer 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"
            }
        })
            .then(function (response) {
                console.log(response.status);
                console.log(response.data);
                const message = response.data;
                output.innerHTML = "";
                displayAnswer(message.choices[0].text);
                //console.log(message.choices[0].text.split(" "))
            })
            .catch(function (error) {
                if(error.response.status === 429){
                    //swal("An Error Occurred!", "Insufficient Quota");
                    displayAnswer("Insufficient Quota. Putangina mo di na kita masasagot hayop ka")
                }
                else {
                    displayAnswer("Putangina mo nag error na")
                }
            });
        
    }

    function displayAnswer(messages)
    {

        //output.innerHTML = "AI: ";
        //    messages.forEach(message => {
        //        setTimeout( function(){
        //            output.innerHTML += message + " ";
        //        },1000)
        //    })

        var typed = new Typed('#output', {
            strings: ["AI. . . . .",messages],
            typeSpeed: 30
        });
        setTimeout(function(){
            input.val(getNextStatement())
        },3000)
    }
    function showConfetti() {
        const jsConfetti = new JSConfetti();

        jsConfetti.addConfetti({
            emojis: ['🌈', '⚡️', '💥', '✨', '💫', '🌸']
        })
    }
</script>

Views/Sample/Cat.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="pagetitle">
    <h1>Facts About Cat</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">Cat</li>
        </ol>
    </nav>
</div>

@*<div class="card">
    <div class="card-body">
        <h5 class="card-title">Pokemon <img src="http://www.pngmart.com/files/2/Pokeball-PNG-Image.png" class="bg-light" width="50" height="50"></h5>
        <div id="pokemon_count">Total Pokemon:</div>

        <table id="datatable"  class="table table-borderless">
            <thead>
                <tr>
                    <th scope="col">Pokemon Name</th>
                    <th scope="col">Url</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody id="table">
            </tbody>
        </table>

    </div>
</div>*@
<section class="section">
    <div class="container">
        <center>
            <img src="https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif" class="bg-light" width="200" height="200">
            <form class="mt-3" id="catForm" novalidate>
                <button type"submit" class="btn btn-lg rounded rounded-pill btn-outline-primary">
                    Next <i class="fa-arrow-right"></i>
                </button>
            </form>
            <h1 id="fact">
            </h1>
        </center>
    </div>
</section>


@*<script>
    $(document).ready(function () {
        let url = "https://catfact.ninja/fact"
        console.log("Ok Ready")
        fetchData(url);
        $("#catForm").on("submit", function (e) {
            e.preventDefault();
            fetchData(url);
            showConfetti()
        })


        function fetchData(url = 'https://catfact.ninja/fact') {
            axios.get(url)
                .then(function (response) {
                    // handle success
                    console.log(response.data);
                    displayCatFact(response.data.fact);
                })
                .catch(function (error) {
                    // handle error
                    console.log(error);
                    displayCatFact(error)
                })
                .then(function () {
                    // always executed
                });
        }

        function displayCatFact(fact) {
            var typed = new Typed('#fact', {
                strings: ["Fact:...", fact],
                typeSpeed: 20
            });
        }
        function showConfetti() {
            const jsConfetti = new JSConfetti();

                jsConfetti.addConfetti({
                    emojis: ['🌈', '⚡️', '💥', '✨', '💫', '🌸']
                })
        }
    })
</script>*@
<script src="~/js/cat.js" asp-append-version="true"></script>

Views/Sample/CoinDesk.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="pagetitle">
    <h1>CoinDesk Update</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">Cat</li>
        </ol>
    </nav>
</div>

<section class="section">
        <div class="container " id="coindesk">
            <div class="jumbotron">
                <h4 id="chartname"></h4>
                <p class="lead">
                    <strong>
                    Date Today:</strong><span id="time"></span></p>

                <div id="body">

                </div>
                <hr class="my-4">
            <p class="lead display-7" id="disclaimer">
                </p>
            </div>
        </div>
</section>



<script src="~/js/coindesk.js" asp-append-version="true"></script>

Views/Sample/Gender.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="pagetitle">
    <h1>Gender Perediction</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">Gender Prediction</li>
        </ol>
    </nav>
</div>

<section class="section">
    <div class="container " id="">
        <div class="card">
            <div class="card-header">
                Gender Perediction
            </div>

            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                            <div class="form-group mb-3">
                                <label label-for="text">Input Name</label>
                                <input type="text" name="name" id="name" class="form-control" />
                            </div>
                            <button type="button" id="submitBtn" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div id="result">

                </div>
            </div>
         </div>
    </div>
</section>



<script src="~/js/gender.js" asp-append-version="true"></script>

Views/Sample/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{

}

<div class="container-xxl">
    <center><h1>Sample Crud</h1></center>
    <button type="button" class="btn btn-primary float-lg-end" data-bs-toggle="modal" data-bs-target="#viewModal">
        Add new
    </button>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Date Created</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            @foreach (Practice practice in ViewBag.practices)
            {
                <tr>
                    <td id="practice_id"> @practice.ID</td>
                    <td> @practice.Firstname</td>
                    <td> @practice.Lastname</td>
                    <td> @practice.Email</td>

                    <td> @practice.DateToday</td> @*Date Created*@
                    <td>
                        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#editModal-@practice.ID">View</button>
                        <a class="btn btn-danger" asp-action="Delete" asp-controller="Sample" asp-route-id="@practice.ID">Delete</a>
                    </td>

                </tr>
            }

        </tbody>
    </table>
</div>

@Html.Partial("_editPracticeModalPartial")
@*
<div class="container-xxl">
    <table class="table">
        <thead>
            <tr>
                <th>Sample Array of String</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in ViewBag.str_output)
            {
              <tr>
                  <td> @item</td>
              </tr>
            }

        </tbody>
    </table>
</div>
*@
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade blur" id="viewModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form asp-action="Create" asp-controller="Sample" method="post">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Sample </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                
                    <div class="form-group">
                        <label for="exampleInputEmail1">Firstname</label>
                        <input type="text" name="firstname" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Firstname">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Last name</label>
                        <input type="text" name="lastname" class="form-control" id="exampleInputPassword1" placeholder="Enter Last Name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Email</label>
                        <input type="email" name="email" class="form-control" id="exampleInputPassword1" placeholder="Enter Email">
                    </div>

                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            </form>
        </div>
    </div>
</div>

<div id="modal_edit">

</div>

<script type="text/javascript">
    $(document).ready(function(){
        console.log('ready') 
    });
    function select(id) {
        var url = `@Url.Action("Edit","Sample")/${id}`;
        fetchData(url)

    }


    async function fetchData(url){
        var response = await fetch(url)
        .then(res =>res.json())
        .then(data => showModal(data))

        showModal()
    }

    function showModal(data)
    {
        $("#modal_edit").html(`
            <div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                        <form asp-action="Edit" asp-controller="Sample" asp-route-id="${data.id}" method="post">
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Firstname</label>
                                <input type="text" name="firstname" class="form-control" value="${data.firstname}" placeholder="Enter Firstname">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Last name</label>
                                <input type="text" name="lastname" class="form-control" value="${data.lastname}" placeholder="Enter Last Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Email</label>
                                <input type="email" name="email" class="form-control" value="${data.email}" placeholder="Enter Email">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Date Created</label>
                                <input type="text" class="form-control" value="${data.dateToday}" placeholder="Enter Email" disabled>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-outline-primary">Edit</button>
                            <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Cancel</button>

                        </div>
                    </form>
                </div>
            </div>
        </div>
        `)

        $("#editModal").modal();
    }
</script>

Views/Sample/Pokemon.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="pagetitle">
    <h1>Pokemon<img src="http://www.pngmart.com/files/2/Pokeball-PNG-Image.png" class="bg-light" width="50" height="50"></h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
            <li class="breadcrumb-item active">Pokemon</li>
        </ol>
    </nav>
</div>
<div id="results">
    
</div>

@*<div class="card">
    <div class="card-body">
        <h5 class="card-title">Pokemon <img src="http://www.pngmart.com/files/2/Pokeball-PNG-Image.png" class="bg-light" width="50" height="50"></h5>
        <div id="pokemon_count">Total Pokemon:</div>

        <table id="datatable"  class="table table-borderless">
            <thead>
                <tr>
                    <th scope="col">Pokemon Name</th>
                    <th scope="col">Url</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody id="table">
            </tbody>
        </table>

    </div>
</div>*@
<section class="section">
    
    
    @*<div class="d-flex justify-content-left">
        <div class="input-group py-3">
            <div class="form-outline">
                <label class="form-label" for="form1">Search</label>
                <input type="search" id="search" class="form-control" />
            </div>
        </div>
    </div>*@
    <div id="cards" class="row">
    </div>
    <div class="btn-group float-end" role="group">
        <button id="prevBtn" class="btn btn-ghost-danger"><i class="fa fa-arrow-left"></i>Previous</button>
        <button id="nextBtn" class="btn btn-ghost-success"><i class="fa fa-arrow-right"></i>Next</button>
    </div>
</section>


<!-- Modal -->
<div class="modal fade" id="viewPokemonModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pokemon_name">Pokemon Name</h5>
            </div>
            <div id="pokemon_details" class="modal-body">
                <div class=" d-flex justify-content-center">
                    <button class="btn btn-primary" type="button" disabled>
                        <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true">Loading...</span>
                    </button>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script src="~/js/pokemon.js" asp-append-version="true"></script>

Views/Sample/_editPracticeModalPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@foreach(Practice practice in ViewBag.practices)
{
    <div class="modal fade" id="editModal-@practice.ID" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form asp-action="Edit" asp-controller="Sample" asp-route-id="@practice?.ID" method="post">
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Firstname</label>
                            <input type="text" name="firstname" class="form-control" value="@practice?.Firstname" placeholder="Enter Firstname">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Last name</label>
                            <input type="text" name="lastname" class="form-control" value="@practice?.Lastname" placeholder="Enter Last Name">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Email</label>
                            <input type="email" name="email" class="form-control" value="@practice?.Email" placeholder="Enter Email">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Date Created</label>
                            <input type="text" class="form-control" value="@practice?.DateToday" placeholder="Enter Email" disabled>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-outline-primary">Edit</button>
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">Cancel</button>
                        
                    </div>
                </form>
            </div>
        </div>
    </div>
}